# SPDX-FileCopyrightText: 2025 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.bumpversion]
current_version = "0.1.6"

[[tool.bumpversion.files]]
filename = "docs/man/man1/randgen.1.adoc"
