// SPDX-FileCopyrightText: 2025 Shun Sakai
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

= How to Build

== Prerequisites

.To build *randgen*, you will need the following dependencies
* https://doc.rust-lang.org/stable/cargo/[Cargo] (v1.85.0 or later)

.To build a man page, you will need the following additional dependencies
* https://asciidoctor.org/[Asciidoctor]

== Building from source

.To clone the repository
[source,sh]
----
git clone https://github.com/sorairolake/randgen.git
cd randgen
----

.To build a package
[source,sh]
----
just build
----

.To find the directory where a man page are generated
[source,sh]
----
fd -t directory out ./target/*/build/randgen-*
----

== Crate features

`base64`::

  Enable encoding the generated bytes as base64. This is enabled by default.

`hc`::

  Enable the use of HC-128-based RNG as a PRNG. This is enabled by default.

`hex`::

  Enable encoding the generated bytes as hex string. This is enabled by default.

`isaac`::

  Enable the use of ISAAC RNGs as a PRNG. This is enabled by default.

`mt`::

  Enable the use of Mersenne Twister RNGs as a PRNG. This is enabled by default.

`pcg`::

  Enable the use of PCG RNGs as a PRNG. This is enabled by default.

`sfc`::

  Enable the use of SFC RNGs as a PRNG. This is enabled by default.

`xorshift`::

  Enable the use of Xorshift RNG as a PRNG. This is enabled by default.
