// SPDX-FileCopyrightText: 2025 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= randgen(1)
// Specify in UTC.
:docdate: 2025-03-10
:revnumber: 0.1.0
:doctype: manpage
:mansource: randgen {revnumber}
:manmanual: General Commands Manual
:enwp-article-url: https://en.wikipedia.org/wiki
:isaac-url: https://www.burtleburtle.net/bob/rand/isaacafa.html
:mt-url: https://www.math.sci.hiroshima-u.ac.jp/m-mat/MT/emt.html
:pcg-url: https://www.pcg-random.org/
:sfc-url: https://pracrand.sourceforge.net/RNG_engines.txt
:chacha-url: https://cr.yp.to/chacha.html
:xorshift-url: https://prng.di.unimi.it/
:hc-128-url: {enwp-article-url}/HC-128
:base64-url: {enwp-article-url}/Base64
:getrandom-man-page-url: https://man7.org/linux/man-pages/man2/getrandom.2.html
:sysexits-man-page-url: https://man.openbsd.org/sysexits
:repo-url: https://github.com/sorairolake/randgen

== NAME

randgen - generate pseudo-random bytes

== SYNOPSIS

*{manname}* [_OPTION_]... _BYTES_

== DESCRIPTION

*{manname}* is a tool which generates random bytes using a pseudorandom number
generator (PRNG). The generated bytes will be output to standard output.

.Supported pseudorandom number generators (PRNGs)
* {isaac-url}[ISAAC] RNGs (if enabled at compile time)
* {mt-url}[Mersenne Twister] RNGs (if enabled at compile time)
* {pcg-url}[PCG] RNGs (if enabled at compile time)
* {sfc-url}[SFC] RNGs (if enabled at compile time)
* {xorshift-url}[Xorshift] family
** SplitMix64 RNG
** Xorshift RNG (if enabled at compile time)
** xoroshiro RNGs
** xoshiro RNGs

.Supported cryptographically secure pseudorandom number generators (CSPRNGs)
* {chacha-url}[ChaCha]-based RNGs
* {hc-128-url}[HC-128]-based RNG (if enabled at compile time)

== POSITIONAL ARGUMENTS

_BYTES_::

  Number of bytes to generate. _BYTES_ can be suffixed with the symbol (B) and
  the byte prefix (such as Ki and M). If only a numeric value is specified for
  _BYTES_, it is the same as specifying the symbol without the byte prefix.

== OPTIONS

*-f*, *--format* _FORMAT_::

  Output in the specified output format.

  The possible values are:{blank}:::

    *raw*::::

      Encode the generated bytes as raw bytes. This is the default value.

    *base64*::::

      Encode the generated bytes as {base64-url}[base64]. This value is
      available if the `base64` feature is enabled at compile time.

    *hex*::::

      Encode the generated bytes as hex string. This value is available if the
      `hex` feature is enabled at compile time.

*-r*, *--random-number-generator* _RNG_::

  Random number generator to use.

  The possible values are:{blank}:::

    *chacha8*::::

      A CSPRNG that uses the ChaCha8 algorithm.

    *chacha12*::::

      A CSPRNG that uses the ChaCha12 algorithm. This is the default value.

    *chacha20*::::

      A CSPRNG that uses the ChaCha20 algorithm.

    *hc128*::::

      A CSPRNG that uses the HC-128 algorithm. This value is available if the
      `hc` feature is enabled at compile time.

    *isaac*::::

      A PRNG that uses the ISAAC algorithm. This value is available if the
      `isaac` feature is enabled at compile time.

    *isaac64*::::

      A PRNG that uses the ISAAC-64 algorithm. This value is available if the
      `isaac` feature is enabled at compile time.

    *mt*::::

      The MT19937 PRNG. This value is available if the `mt` feature is enabled
      at compile time.

    *mt64*::::

      The MT19937-64 PRNG. This value is available if the `mt` feature is
      enabled at compile time.

    *pcg32*::::

      The pcg32 PRNG. This value is available if the `pcg` feature is enabled
      at compile time.

    *pcg64*::::

      The pcg64 PRNG. This value is available if the `pcg` feature is enabled
      at compile time.

    *pcg64dxsm*::::

      The PCG64DXSM PRNG. This value is available if the `pcg` feature is
      enabled at compile time.

    *pcg64mcg*::::

      The pcg64_fast PRNG. This value is available if the `pcg` feature is
      enabled at compile time.

    *sfc32*::::

      The sfc32 PRNG. This value is available if the `sfc` feature is enabled
      at compile time.

    *sfc64*::::

      The sfc64 PRNG. This value is available if the `sfc` feature is enabled
      at compile time.

    *splitmix64*::::

      The splitmix64 PRNG.

    *xorshift*::::

      The Xorshift PRNG. This value is available if the `xorshift` feature is
      enabled at compile time.

    *xoroshiro64{asterisk}*::::

      The xoroshiro64{asterisk} PRNG.

    *xoroshiro64{asterisk}*::::

      The xoroshiro64{asterisk}{asterisk} PRNG.

    *xoroshiro128+*::::

      The xoroshiro128+ PRNG.

    *xoroshiro128++*::::

      The xoroshiro128++ PRNG.

    *xoroshiro128{asterisk}{asterisk}*::::

      The xoroshiro128{asterisk}{asterisk} PRNG.

    *xoshiro128+*::::

      The xoshiro128+ PRNG.

    *xoshiro128++*::::

      The xoshiro128++ PRNG.

    *xoshiro128{asterisk}{asterisk}*::::

      The xoshiro128{asterisk}{asterisk} PRNG.

    *xoshiro256+*::::

      The xoshiro256+ PRNG.

    *xoshiro256++*::::

      The xoshiro256++ PRNG.

    *xoshiro256{asterisk}{asterisk}*::::

      The xoshiro256{asterisk}{asterisk} PRNG.

    *xoshiro512+*::::

      The xoshiro512+ PRNG.

    *xoshiro512++*::::

      The xoshiro512++ PRNG.

    *xoshiro512{asterisk}{asterisk}*::::

      The xoshiro512{asterisk}{asterisk} PRNG.

*-s*, *--seed* _NUMBER_::

  Random seed to use. If this option is not specified, the RNG seeded via
  random data from system sources such as the
  {getrandom-man-page-url}[`getrandom`] system call on Linux.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

*--generate-completion* _SHELL_::

  Generate shell completion. The completion is output to standard output.

  The possible values are:{blank}:::

    *bash*::::

      Bash.

    *elvish*::::

      Elvish.

    *fish*::::

      fish.

    *nushell*::::

      Nushell.

    *powershell*::::

      PowerShell.

    *zsh*::::

      Zsh.

== EXIT STATUS

*0*::

  Successful program execution.

*1*::

  An error occurred.

*2*::

  An error occurred while parsing command-line arguments.

Exit statuses other than these are defined by
{sysexits-man-page-url}[`<sysexits.h>`].

== NOTES

Source repository:{blank}::

  {repo-url}

== EXAMPLES

Generate 1 KiB of random bytes:{blank}::

  $ *randgen 1KiB*

Encode the generated bytes as base64:{blank}::

  $ *randgen -f base64 256*

Use the pcg64 as a PRNG:{blank}::

  $ *randgen -r pcg64 "2 MB"*

Use the specified random seed:{blank}::

  $ *randgen -f hex -r sfc32 -s 8 32B*

== REPORTING BUGS

Report bugs to:{blank}::

  {repo-url}/issues

== COPYRIGHT

Copyright (C) 2025 Shun Sakai

. This program is distributed under the terms of either the Apache License 2.0
  or the MIT License.
. This manual page is distributed under the terms of the Creative Commons
  Attribution 4.0 International Public License.

This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.

== SEE ALSO

*openssl-rand*(1)
